name: Release
on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
      - name: Run Semantic Release
        run: |
          npm install semantic-release
          npx semantic-release --debug --no-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
